MANIFEST.in, docker/entrypoint.sh, prepare.py, requirements.txt, setup.py
fixed #17 
Installing BBc-1 package by pip take effects only on Dockerfile_pip.
=> FIX #17 - Conflict with source code and pip module

bbc1/common/bbclib.py, bbc1/common/libbbcsig/libbbcsig.c
Moved sign/verify method from BBcSignature class to KeyPair class, and also implement a function of reading a private key in pen format.
=> Refactoring bbclib.py and its c-library

bbc1/common/bbclib.py, bbc1/common/libbbcsig/libbbcsig.c
FIX #19
change the branch to merge into from develop to 0.8-pre
=> #9 implement inserted_notification

docker/docker-bbc1.sh
used "git archive" instead of "git archive-all" on docker-bbc1.sh
modified indent on docker-bbc1.sh
=> FIX #21 - 'archive-all' is not a git command

bbc1/core/bbc_core.py, tests/test_bbc_app_multi_core_notification.py
Cancelation of notification did not work well. So, I've fixed the bug.
=> FIX #25 bug fix of inserted_notification

examples/file_proof/README.md
=> Fix Typo: examples/file_proof/README.md

docs/how_to_use_in_nat_environment.md
I added a guideline to deploy BBc-1 in NAT environment like Microsoft Azure. It also explains the new option ipv4addr of bbc_core.py.
=> Added a document for the usage of BBc-1 in NAT environments

bbc1/core/bbc_core.py, examples/file_proof/file_proof.py, setup.py, utils/bbc_ping.py, utils/bbc_system_conf.py
Please accept this change for the registration of v0.8.0.1 to PyPI
=> Updated setup.py

bbc1/common/bbclib.py, bbc1/common/libbbcsig/libbbcsig.c, bbc1/common/libbbcsig/libbbcsig.h
Passed 50M stress test for sining and verification
=> Fixed an ECDSA signing bug due to inappropriate padding to signature element

examples/file_proof/file_proof.py
Accommodated v0.10 changes to file_proof example, fixing #72 and other potential problems.
=> fixed #72 (file_proof to accommodate v0.10 changes).

MANIFEST.in, prepare.py, prepare.sh, setup.py, third_party/libbbcsig/Makefile, third_party/libbbcsig/dllmain.c, third_party/libbbcsig/libbbcsig.c, third_party/libbbcsig/libbbcsig.def, third_party/libbbcsig/libbbcsig.h, third_party/libbbcsig/pybbcsig.py, third_party/libbbcsig/test_ecdsa.py, third_party/libbbcsig/test_pybbcsig.py
fix: unable to compile libbbcsig.so
=> fix: unable to compile libbbcsig.so

prepare.sh
fix: failed to create libbbcsig.so
=> fix: failed to create libbbcsig.so

bbc1/core/bbc_core.py
It seems that domain configuration was not properly referred to.
=> fix for #78.

prepare.sh, setup.py
fix: failed to compile libbbcsig.so on Ubuntu 16.04
=> fix: failed to compile libbbcsig.so on Ubuntu 16.04

docker/Dockerfile_git, docker/Dockerfile_pip, requirements.txt, setup.py
fix : dockerfile (for git install and pip install)
=> fix : dockerfile (for git install and pip install)

docker/Dockerfile_git, docker/Dockerfile_pip
fix : docker base image (ubuntu latest -> 16.04)
=> fix : docker base image (ubuntu latest -> 16.04)

docs/BBc1_programming_guide_v1.0_ja.md, utils/bbc_domain_config.py
Syntax error has occured by using bbc_domain_update.py to write config file.
This is caused without "#!/bin/sh".
This commit improve it and add Copyright of beyond-blockchain.org.
=> [update] bug fix for bbc_domain_update.py

prepare.sh, setup.py
[fix] failed to compile openssl on linux environment
=> [fix] failed to compile openssl on linux environment

docs/BBc-1_transaction_data_ja.md
modified typo and figure captions
=> docs : modified typo

README.md, README.rst
Reverts beyond-blockchain/bbc1#125
Sorry, I wrongly press merge button, so reverted.
=> Revert "typo in docs"
